### ISSUE TITLE
Search for app names containing more than one underscore does fail

### ISSUE THREAD

**Issue by oli666** [mtreadwell/alterryx#1]
Hi,
I encounter a reproducible issue using "search" as a "request_param" when looking for app names containing more than one underscore. E.g., 

"APP" -> works
"APP_1" -> works
"APP_1_2" -> does not work

I can reproduce that by using the Alteryx API directly on the web page containing the interactive API documentation. I tried Alteryx 11.0 and 11.3; same results.
Any hints what might be the root cause for that? 
Thanks,
Oliver

**Comment by mtreadwell** [comment]
Thanks for bringing this to my attention. I am using the interactive Gallery API docs at https://gallery.alteryx.com/api-docs/ except for my internal Alteryx Gallery. Both the packageType and search parameters are not acting as expected. This leads me to believe that the issue is either on the Alteryx API end.

I have reached out to Alteryx support to try and shed some light on this situation. I will update here when it is resolved.

**Comment by oli666** [comment]
I use the following workaround for the time being to search for the full name of an app (which essentially is the most important "search" scenario for me);  

library(purrr)
subscriptions <- get_app()
app <- subscriptions[lapply(subscriptions, function(x) x[["metaInfo"]][["name"]]) == appName] 
app <- flatten(app)
app <- as.alteryx_app(app)

**Comment by mtreadwell** [comment]
This is working for me now with the latest updates to master
